# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package Math::R;
use base qw(Exporter);
use base qw(DynaLoader);
package Math::Rc;
bootstrap Math::R;
package Math::R;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package Math::R;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package Math::R;

*R_pow = *Math::Rc::R_pow;
*R_pow_di = *Math::Rc::R_pow_di;
*norm_rand = *Math::Rc::norm_rand;
*unif_rand = *Math::Rc::unif_rand;
*R_unif_index = *Math::Rc::R_unif_index;
*exp_rand = *Math::Rc::exp_rand;
*set_seed = *Math::Rc::set_seed;
*get_seed = *Math::Rc::get_seed;
*dnorm = *Math::Rc::dnorm;
*pnorm = *Math::Rc::pnorm;
*qnorm = *Math::Rc::qnorm;
*rnorm = *Math::Rc::rnorm;
*pnorm_both = *Math::Rc::pnorm_both;
*dunif = *Math::Rc::dunif;
*punif = *Math::Rc::punif;
*qunif = *Math::Rc::qunif;
*runif = *Math::Rc::runif;
*dgamma = *Math::Rc::dgamma;
*pgamma = *Math::Rc::pgamma;
*qgamma = *Math::Rc::qgamma;
*rgamma = *Math::Rc::rgamma;
*log1pmx = *Math::Rc::log1pmx;
*log1pexp = *Math::Rc::log1pexp;
*log1mexp = *Math::Rc::log1mexp;
*lgamma1p = *Math::Rc::lgamma1p;
*logspace_add = *Math::Rc::logspace_add;
*logspace_sub = *Math::Rc::logspace_sub;
*logspace_sum = *Math::Rc::logspace_sum;
*dbeta = *Math::Rc::dbeta;
*pbeta = *Math::Rc::pbeta;
*qbeta = *Math::Rc::qbeta;
*rbeta = *Math::Rc::rbeta;
*dlnorm = *Math::Rc::dlnorm;
*plnorm = *Math::Rc::plnorm;
*qlnorm = *Math::Rc::qlnorm;
*rlnorm = *Math::Rc::rlnorm;
*dchisq = *Math::Rc::dchisq;
*pchisq = *Math::Rc::pchisq;
*qchisq = *Math::Rc::qchisq;
*rchisq = *Math::Rc::rchisq;
*dnchisq = *Math::Rc::dnchisq;
*pnchisq = *Math::Rc::pnchisq;
*qnchisq = *Math::Rc::qnchisq;
*rnchisq = *Math::Rc::rnchisq;
*df = *Math::Rc::df;
*pf = *Math::Rc::pf;
*qf = *Math::Rc::qf;
*rf = *Math::Rc::rf;
*dt = *Math::Rc::dt;
*pt = *Math::Rc::pt;
*qt = *Math::Rc::qt;
*rt = *Math::Rc::rt;
*dbinom_raw = *Math::Rc::dbinom_raw;
*dbinom = *Math::Rc::dbinom;
*pbinom = *Math::Rc::pbinom;
*qbinom = *Math::Rc::qbinom;
*rbinom = *Math::Rc::rbinom;
*rmultinom = *Math::Rc::rmultinom;
*dcauchy = *Math::Rc::dcauchy;
*pcauchy = *Math::Rc::pcauchy;
*qcauchy = *Math::Rc::qcauchy;
*rcauchy = *Math::Rc::rcauchy;
*dexp = *Math::Rc::dexp;
*pexp = *Math::Rc::pexp;
*qexp = *Math::Rc::qexp;
*rexp = *Math::Rc::rexp;
*dgeom = *Math::Rc::dgeom;
*pgeom = *Math::Rc::pgeom;
*qgeom = *Math::Rc::qgeom;
*rgeom = *Math::Rc::rgeom;
*dhyper = *Math::Rc::dhyper;
*phyper = *Math::Rc::phyper;
*qhyper = *Math::Rc::qhyper;
*rhyper = *Math::Rc::rhyper;
*dnbinom = *Math::Rc::dnbinom;
*pnbinom = *Math::Rc::pnbinom;
*qnbinom = *Math::Rc::qnbinom;
*rnbinom = *Math::Rc::rnbinom;
*dnbinom_mu = *Math::Rc::dnbinom_mu;
*pnbinom_mu = *Math::Rc::pnbinom_mu;
*qnbinom_mu = *Math::Rc::qnbinom_mu;
*rnbinom_mu = *Math::Rc::rnbinom_mu;
*dpois_raw = *Math::Rc::dpois_raw;
*dpois = *Math::Rc::dpois;
*ppois = *Math::Rc::ppois;
*qpois = *Math::Rc::qpois;
*rpois = *Math::Rc::rpois;
*dweibull = *Math::Rc::dweibull;
*pweibull = *Math::Rc::pweibull;
*qweibull = *Math::Rc::qweibull;
*rweibull = *Math::Rc::rweibull;
*dlogis = *Math::Rc::dlogis;
*plogis = *Math::Rc::plogis;
*qlogis = *Math::Rc::qlogis;
*rlogis = *Math::Rc::rlogis;
*dnbeta = *Math::Rc::dnbeta;
*pnbeta = *Math::Rc::pnbeta;
*qnbeta = *Math::Rc::qnbeta;
*dnf = *Math::Rc::dnf;
*pnf = *Math::Rc::pnf;
*qnf = *Math::Rc::qnf;
*dnt = *Math::Rc::dnt;
*pnt = *Math::Rc::pnt;
*qnt = *Math::Rc::qnt;
*ptukey = *Math::Rc::ptukey;
*qtukey = *Math::Rc::qtukey;
*dwilcox = *Math::Rc::dwilcox;
*pwilcox = *Math::Rc::pwilcox;
*qwilcox = *Math::Rc::qwilcox;
*rwilcox = *Math::Rc::rwilcox;
*dsignrank = *Math::Rc::dsignrank;
*psignrank = *Math::Rc::psignrank;
*qsignrank = *Math::Rc::qsignrank;
*rsignrank = *Math::Rc::rsignrank;
*gammafn = *Math::Rc::gammafn;
*lgammafn = *Math::Rc::lgammafn;
*lgammafn_sign = *Math::Rc::lgammafn_sign;
*dpsifn = *Math::Rc::dpsifn;
*psigamma = *Math::Rc::psigamma;
*digamma = *Math::Rc::digamma;
*trigamma = *Math::Rc::trigamma;
*tetragamma = *Math::Rc::tetragamma;
*pentagamma = *Math::Rc::pentagamma;
*beta = *Math::Rc::beta;
*lbeta = *Math::Rc::lbeta;
*choose = *Math::Rc::choose;
*lchoose = *Math::Rc::lchoose;
*bessel_i = *Math::Rc::bessel_i;
*bessel_j = *Math::Rc::bessel_j;
*bessel_k = *Math::Rc::bessel_k;
*bessel_y = *Math::Rc::bessel_y;
*bessel_i_ex = *Math::Rc::bessel_i_ex;
*bessel_j_ex = *Math::Rc::bessel_j_ex;
*bessel_k_ex = *Math::Rc::bessel_k_ex;
*bessel_y_ex = *Math::Rc::bessel_y_ex;
*imax2 = *Math::Rc::imax2;
*imin2 = *Math::Rc::imin2;
*fmax2 = *Math::Rc::fmax2;
*fmin2 = *Math::Rc::fmin2;
*sign = *Math::Rc::sign;
*fprec = *Math::Rc::fprec;
*fround = *Math::Rc::fround;
*fsign = *Math::Rc::fsign;
*ftrunc = *Math::Rc::ftrunc;
*cospi = *Math::Rc::cospi;
*sinpi = *Math::Rc::sinpi;
*tanpi = *Math::Rc::tanpi;
*R_finite = *Math::Rc::R_finite;

# ------- VARIABLE STUBS --------

package Math::R;

*__STDC_WANT_IEC_60559_FUNCS_EXT__ = *Math::Rc::__STDC_WANT_IEC_60559_FUNCS_EXT__;
*R_VERSION_STRING = *Math::Rc::R_VERSION_STRING;
*HAVE_EXPM1 = *Math::Rc::HAVE_EXPM1;
*HAVE_HYPOT = *Math::Rc::HAVE_HYPOT;
*HAVE_LOG1P = *Math::Rc::HAVE_LOG1P;
*HAVE_WORKING_LOG1P = *Math::Rc::HAVE_WORKING_LOG1P;
*M_E = *Math::Rc::M_E;
*M_LOG2E = *Math::Rc::M_LOG2E;
*M_LOG10E = *Math::Rc::M_LOG10E;
*M_LN2 = *Math::Rc::M_LN2;
*M_LN10 = *Math::Rc::M_LN10;
*M_PI = *Math::Rc::M_PI;
*M_2PI = *Math::Rc::M_2PI;
*M_PI_2 = *Math::Rc::M_PI_2;
*M_PI_4 = *Math::Rc::M_PI_4;
*M_1_PI = *Math::Rc::M_1_PI;
*M_2_PI = *Math::Rc::M_2_PI;
*M_2_SQRTPI = *Math::Rc::M_2_SQRTPI;
*M_SQRT2 = *Math::Rc::M_SQRT2;
*M_SQRT1_2 = *Math::Rc::M_SQRT1_2;
*M_SQRT_3 = *Math::Rc::M_SQRT_3;
*M_SQRT_32 = *Math::Rc::M_SQRT_32;
*M_LOG10_2 = *Math::Rc::M_LOG10_2;
*M_SQRT_PI = *Math::Rc::M_SQRT_PI;
*M_1_SQRT_2PI = *Math::Rc::M_1_SQRT_2PI;
*M_SQRT_2dPI = *Math::Rc::M_SQRT_2dPI;
*M_LN_2PI = *Math::Rc::M_LN_2PI;
*M_LN_SQRT_PI = *Math::Rc::M_LN_SQRT_PI;
*M_LN_SQRT_2PI = *Math::Rc::M_LN_SQRT_2PI;
*M_LN_SQRT_PId2 = *Math::Rc::M_LN_SQRT_PId2;
*FALSE = *Math::Rc::FALSE;
*TRUE = *Math::Rc::TRUE;
*N01_kind = *Math::Rc::N01_kind;
1;
